server:
   port : 9002
   
spring:     
  application:
    name: USER-SERVICE
  zipkin:
   base-url: http://127.0.0.1:9411/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
   hostname: localhost
   