server:
 port: 9005

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
   hostname: localhost
   
spring:
 application:
  name: CONFIG-SERVICE

  
 cloud:
  config:
   server:
     git:
       uri: https://github.com/khadija1604/configuration
      